name: Build & Test

on:
  push:
    branches:
      - dev

  pull_request:
    branches-ignore:
      - 'changeset-release/main'

    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18, 20]
    # if: ${{ github.ref != 'refs/heads/changeset-release/main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Type check
        run: pnpm tc

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
